import { ref, computed } from "vue";

const courses = [
  {
    title: "Complete Java Developer Course from Scratch",
    issuer: "Udemy",
  },
  {
    title: "Advanced Android Mobile Application",
    issuer: "Udemy",
  },
  {
    title:
      "Advanced Ethical Hacker: Penetration Testing & Privilege Escalation",
    issuer: "Udemy",
  },
  {
    title: "Advanced Styling with Responsive Design",
    issuer: "University of Michigan-Coursera",
  },
  {
    title: "Android Mobile Application Course: Kotlin & Java",
    issuer: "Udemy",
  },
  {
    title:
      "Artificial General Intelligence: The Technology, Impact, and Ethics",
    issuer: "LinkedIn Learning",
  },
  {
    title: "Automating Your Work with Custom GPTs (No Code Required)",
    issuer: "LinkedIn Learning",
  },
  {
    title: "AWS Certified Cloud Practitioner",
    issuer: "Amazon Web Services (AWS) Coursera",
  },
  {
    title: "AWS Cloud Practitioner Essentials",
    issuer: "Amazon Web Services (AWS) Coursera",
  },
  {
    title: "AWS Fundamentals Lab Series",
    issuer: "Amazon Web Services (AWS) Coursera",
  },
  {
    title: "AWS re/Start Course",
    issuer: "Amazon Web Services (AWS)",
  },
  {
    title: "AWS re/Start Graduate",
    issuer: "Amazon Web Services (AWS)",
  },
  {
    title: "Becoming an Ethical Hacker: Mobile Applications and Phones",
    issuer: "Udemy",
  },
  {
    title: "Becoming an Ethical Hacker: Web Penetration Testing and Bug Bounty",
    issuer: "Udemy",
  },
  {
    title: "BOOST YOUR CAREER WITH AI",
    issuer: "Kiron Open Higher Education",
  },
  {
    title: "Build a free website with WordPress",
    issuer: "Coursera",
  },
  {
    title: "Creating a WordPress Website: Blog, E-Commerce, Corporate",
    issuer: "Udemy",
  },
  {
    title: "CSS3",
    issuer: "Hi/Coders",
  },
  {
    title: "Cybersecurity Fundamentals",
    issuer: "IBM SkillsBuild",
  },
  {
    title: "Ethical Hacker Course",
    issuer: "Udemy",
  },
  {
    title: "Explore Emerging Tech",
    issuer: "IBM SkillsBuild",
  },
  {
    title: "Foundations of Linux",
    issuer: "Coursera",
  },
  {
    title: "Front-End Web Development with React",
    issuer: "The Hong Kong University of Science and Technology Coursera",
  },
  {
    title: "Front-End Web UI Frameworks and Tools: Bootstrap 4",
    issuer: "The Hong Kong University of Science and Technology Coursera",
  },
  {
    title: "Full Stack Web Programming",
    issuer: "Hi/Coders",
  },
  {
    title: "Generative AI with Large Language Models",
    issuer: "DeepLearning.AI & Amazon Web Services Coursera",
  },
  {
    title: "Getting Started with Threat Intelligence and Hunting",
    issuer: "IBM SkillsBuild",
  },
  {
    title: "Hands-On AI: Build Your Own GPTs",
    issuer: "LinkedIn Learning",
  },
  {
    title: "How to Boost Your Productivity with AI Tools (2023)",
    issuer: "LinkedIn Learning",
  },
  {
    title: "How to Research and Write Using Generative AI Tools (2023)",
    issuer: "LinkedIn Learning",
  },
  {
    title:
      "IBM SkillsBuild Presents: How to Become a Cybersecurity Professional",
    issuer: "IBM SkillsBuild",
  },
  {
    title: "Interactivity with JavaScript",
    issuer: "University of Michigan Coursera",
  },
  {
    title: "Introduction to CSS3",
    issuer: "University of Michigan Coursera",
  },
  {
    title: "Introduction to Cybersecurity Careers",
    issuer: "IBM / Coursera",
  },
  {
    title: "Introduction to Front-End Development",
    issuer: "Meta Coursera",
  },
  {
    title: "Introduction to HTML5",
    issuer: "University of Michigan Coursera",
  },
  {
    title: "Java",
    issuer: "Sololearn",
  },
  {
    title: "Javascript & Advanced Programming",
    issuer: "Hi/Coders",
  },
  {
    title: "Javascript & Programming Basics",
    issuer: "Hi/Coders",
  },
  {
    title: "Node.js",
    issuer: "Hi/Coders",
  },
  {
    title: "Penetration Testing, Threat Hunting, and Cryptography",
    issuer: "Coursera",
  },
  {
    title: "Product Development using AutoCAD",
    issuer: "Coursera",
  },
  {
    title: "React",
    issuer: "Hi/Coders",
  },
  {
    title: "SAP Professional Fundamentals",
    issuer: "SAP Coursera",
  },
  {
    title: "Terraform Basics: Automate Provisioning of AWS EC2 Instances",
    issuer: "Coursera (Guided Projects) Coursera",
  },
  {
    title: "Terraform for absolute beginners",
    issuer: "Coursera",
  },
  {
    title: "The Most Up-to-Date Spring Course in Turkey: 2025",
    issuer: "Udemy",
  },
  {
    title: "The Potential Power of AI Is Beyond Belief with MattVidPro",
    issuer: "eLearning / Webinar (CompTIA platform)",
  },
  {
    title: "Understanding Bias in AI",
    issuer: "LinkedIn Learning",
  },
  {
    title: "What Is Generative AI?",
    issuer: "LinkedIn Learning",
  },
];

const currentLang = ref("de");

const translations = {
  de: {
    nav: {
      about: "Über mich",
      skills: "Fähigkeiten",
      projects: "Projekte",
      experience: "Erfahrung",
      education: "Ausbildung",
      certificates: "Zertifikate",
      contact: "Kontakt",
    },
    hero: {
      role: "Full Stack Developer",
      greeting: "Hallo, ich bin",
      description:
        "Junior Full Stack Developer. Entwickelt hochperformante Web-Apps mit KI-Unterstützung und modernen Technologien wie Vue.js, Node.js, AWS Cloud, Java (Spring), React, Angular, MySQL, Cybersecurity, Ethical Hacking.",
      viewProjects: "Projekte ansehen",
      contact: "Kontakt",
      scroll: "Scroll",
    },
    about: {
      subtitle: "Wer bin ich?",
      title: "Über mich",
      heading: "Leidenschaftlicher Entwickler & lebenslanges Lernen",
      p1: "Ich bin ein Junior Full-Stack Developer mit einer AWS Cloud Practitioner Zertifizierung und großem Interesse an modernen Webtechnologien sowie Cloud-basierten Lösungen. Zu meinen technischen Interessen gehören Vue.js, React, Angular, Node.js, Java (Spring), MySQL und die AWS Cloud, ebenso wie Grundlagen in Cybersecurity und Ethical Hacking.",
      p2: "In meinem Entwicklungsprozess verfolge ich einen KI-gestützten Ansatz und nutze aktiv Tools wie GitHub Copilot, um die Produktivität zu steigern und die Entwicklung zu beschleunigen. Durch die Arbeit mit Technologien wie Vue.js, Node.js, Java (Spring), React, Angular, MySQL und der AWS Cloud fokussiere ich mich auf die Entwicklung hochperformanter und skalierbarer Webanwendungen, wobei ich sowohl schnelle Prototypen als auch produktionsreife Lösungen liefere.",
      p3: "Meine Entwicklungsphilosophie basiert darauf, sauberen und wartbaren Code zu schreiben, skalierbare Systemarchitekturen zu entwerfen und hervorragende Benutzererfahrungen zu schaffen. Ich engagiere mich für kontinuierliches Lernen, die Erkundung neuer Technologien und die Kombination von Entwicklungs-, Cloud- und Sicherheitswissen, um zuverlässige und effiziente digitale Lösungen zu entwickeln.",
      location: "Standort",
      email: "E-Mail",
      phone: "Telefon",
      languages: "Sprachen",
      cert: "Zertifizierung",
      license: "Führerschein",
      stats: {
        projects: "Projekte abgeschlossen",
        certs: "Zertifizierungen",
        training: "Full Stack Ausbildung",
        teaching: "Jahre Lehrerfahrung",
      },
    },
    skills: {
      subtitle: "Was ich kann",
      title: "Fähigkeiten & Technologien",
    },
    projects: {
      subtitle: "Was ich gebaut habe",
      title: "Projekte",
      live: "Live ansehen",
      items: [
        { title:"CampusAI – AI-Driven Education",
          desc: "KI-gestützte Plattform zur Erstellung von Lernmaterialien, Online-Tests und Feedback. Beinhaltet KI-basierte Lehrerwahl zur optimalen Bedarfsdeckung.",
          date: "In Arbeit",
          logo: "campusai.webp",
          icon: "fas fa-robot",
          iconBg: "bg-blue-900/50",
          iconColor: "text-blue-400",
          tags: ["Next.js", "React.js", "Prisma", "Supabase", "Firebase", "Tailwind V4", "OpenAI", "Vitest"],
          link: "https://www.campusai.ch",
        },
        { title:"SecureDev AI – Security & OWASP Scanner",
          desc: "Sicherheitstest-Plattform mit Node.js Server & Vue.js. Überprüft URLs und Quellcode auf Schwachstellen, bietet OWASP Top 10 Auswertungen und KI-gestützte Fehlerbehebungen mittels API-Key an.",
          date: "2026",
          logo: "sec_ai.png",
          icon: "fas fa-shield-alt",
          iconBg: "bg-red-900/50",
          iconColor: "text-red-400",
          tags: ["Vue.js", "Vite", "Tailwind CSS", "Lucide Vue", "PostCSS", "AI Security"],
          link: "https://secure-dev-ai.vercel.app/",
        },
        { title:"Ali Baba Yöresel – E-Commerce & CRM",
          desc: "Vollständige E-Commerce & CRM-Plattform mit Admin Portal. Konzept, Entwicklung, Deployment und Wartung komplett eigenständig durchgeführt.",
          date: "2026",
          logo: "alibaba.png",
          icon: "fas fa-shopping-cart",
          iconBg: "bg-purple-900/50",
          iconColor: "text-purple-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://www.alibabayoresel.com.tr",
        },
        { title:"Sefa Metzgerei – E-Commerce & Admin Portal",
          desc: "Professionelle E-Commerce Plattform mit Admin-Verwaltung für eine Metzgerei. Vollständig eigenständig entwickelt, deployed und gewartet.",
          date: "2026",
          logo: "sefa_metz.jpg",
          icon: "fas fa-store",
          iconBg: "bg-green-900/50",
          iconColor: "text-green-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://plus-metz.vercel.app",
        },
        { title:"Data Hackdays Uri 2025",
          desc: "Integration Monitoring Projekt. Frontend eigenständig innerhalb von 2 Tagen entwickelt und auf AWS S3 gehostet. Demographische & soziale Daten kombiniert.",
          date: "April 2025",
          logo: "hoi_uri.png",
          icon: "fas fa-chart-bar",
          iconBg: "bg-orange-900/50",
          iconColor: "text-orange-400",
          tags: ["Vue.js", "Vite", "Tailwind CSS", "Leaflet", "FullCalendar", "AWS S3"],
          link: "https://cumathka.github.io/hoi_ui/#/",
        },
        { title:"Design Bees – Angular & Java",
          desc: "Teambasiertes 6-Monats-Projekt mit Java OOP, Angular-Frontend, MySQL-Datenbankverwaltung, CI/CD-Pipelines und Projektmanagement mit Jira.",
          date: "Aug 2022 – Feb 2023",
          logo: "designbees.png",
          icon: "fas fa-code",
          iconBg: "bg-indigo-900/50",
          iconColor: "text-indigo-400",
          tags: ["Java", "Angular", "MySQL", "CI/CD", "Jira", "Scrum"],
          link: "https://designbees.ch/",
        }
      ],
    },
    experience: {
      subtitle: "Meine Laufbahn",
      title: "Berufliche Erfahrung",
      jobs: [
        {
          title: "Freiwilliger Fullstack Developer",
          company: "Design Bees, Zürich (Remote)",
          period: "Aug 2022 – Feb 2023",
          points: [
            "Entwicklung mit Java Spring Boot und Angular",
            "Zusammenarbeit im Team und Teilnahme an Teamaktivitäten",
            "Anwendung gängiger Entwicklungstechniken und Werkzeuge",
          ],
        },
        {
          title: "3-Achsen-CNC-Maschinenbediener",
          company: "Holzverarbeitung, Hatay, Türkei",
          period: "Nov 2019 – Mai 2021",
          points: [
            "Bedienung von 3-Achsen-CNC-Maschinen für Holz",
            "Erstellung von Produktionsplänen",
            "Alphacam 3D-Programm Anwendung",
          ],
        },
        {
          title: "Textil Planungsspezialist",
          company: "Karaman Textile, Samsun, Türkei",
          period: "Dez 2016 – Aug 2017",
          points: [
            "Planung und Koordination von Textilproduktionsprozessen",
            "Optimierung von Produktionsabläufen",
          ],
        },
        {
          title: "Mathematiklehrer",
          company:
            "Staatliche Schulen – Ministerium für Nationale Bildung, Türkei",
          period: "Sep 2007 – Aug 2016",
          points: [
            "Unterricht in Mathematik und Naturwissenschaften",
            "Fortbildung in Bildungstechnologien",
            "Entwicklung von E-Learning-Inhalten",
          ],
        },
      ],
    },
    education: {
      subtitle: "Mein Werdegang",
      title: "Ausbildung",
      items: [
        {
          title: "AWS Re-Start + Cloud Kurs",
          institution: "AWS / Cloud Bootcamp",
          year: "2023",
          items: [
            "AWS Dienste (EC2, S3, IAM)",
            "Cloud-Sicherheit",
            "Terraform & CloudFormation",
            "Automatisierung",
          ],
        },
        {
          title: "Full Stack Web-Entwicklung",
          institution: "Hi-Coders (15 Monate)",
          year: "2022",
          items: [
            "HTML, CSS, JavaScript",
            "React, Angular, Vue.js",
            "Node.js & Java",
            "Responsive Design",
          ],
        },
        {
          title: "Lehramt Mathematik & Naturwiss.",
          institution: "Atatürk Universität, Erzurum",
          year: "2006",
          items: [
            "Pädagogik & Didaktik",
            "Physik, Chemie, Biologie",
            "Computergestützte Mathematik",
            "Laborunterricht",
          ],
        },
      ],
    },
    certificates: {
      subtitle: "Meine Erfolge",
      title: "Zertifikate",
      items: courses,
    },
    contact: {
      subtitle: "Schreib mir",
      title: "Kontakt",
      text: "Ich freue mich auf neue Möglichkeiten. Melde dich gern!",
      name: "Name",
      email: "E-Mail",
      message: "Nachricht",
      send: "Nachricht senden",
      placeholder: {
        name: "Dein Name",
        email: "deine@email.com",
        message: "Deine Nachricht...",
      },
    },
    footer: {
      rights: "© 2025 Cuma Kaya · Altdorf, Schweiz",
      built: "Built with",
    },
  },
  en: {
    nav: {
      about: "About Me",
      skills: "Skills",
      projects: "Projects",
      experience: "Experience",
      education: "Education",
      certificates: "Certificates",
      contact: "Contact",
    },
    hero: {
      role: "Full Stack Developer",
      greeting: "Hello, I am",
      description:
        "Junior Full Stack Developer. Building high-performance web apps with AI-supported development and modern stacks like Vue.js, Node.js, AWS Cloud, Java (Spring), React, Angular, MySQL, Cybersecurity, Ethical Hacking.",
      viewProjects: "View Projects",
      contact: "Contact",
      scroll: "Scroll",
    },
    about: {
      subtitle: "Who am I?",
      title: "About Me",
      heading: "Passionate Developer & Lifelong Learner",
      p1: "I am a Junior Full-Stack Developer with an AWS Cloud Practitioner certification and a strong interest in modern web technologies and cloud-based solutions. My technical interests include Vue.js, React, Angular, Node.js, Java (Spring), MySQL, and AWS Cloud, as well as cybersecurity and ethical hacking fundamentals.",
      p2: "In my development process, I adopt an AI-assisted approach and actively use tools such as GitHub Copilot to improve productivity and accelerate development. By working with technologies like Vue.js, Node.js, Java (Spring), React, Angular, MySQL, and AWS Cloud, I focus on building high-performance and scalable web applications, delivering both rapid prototypes and production-ready solutions.",
      p3: "My development philosophy is based on writing clean and maintainable code, designing scalable system architectures, and creating excellent user experiences. I am committed to continuous learning, exploring new technologies, and combining development, cloud, and security knowledge to build reliable and efficient digital solutions.",
      location: "Location",
      email: "Email",
      phone: "Phone",
      languages: "Languages",
      cert: "Certification",
      license: "Driving License",
      stats: {
        projects: "Projects Completed",
        certs: "Certifications",
        training: "Full Stack Training",
        teaching: "Years Teaching Exp.",
      },
    },
    skills: {
      subtitle: "What I can do",
      title: "Skills & Technologies",
    },
    projects: {
      subtitle: "What I built",
      title: "Projects",
      live: "View Live",
      items: [
        { title:"CampusAI – AI-Driven Education",
          desc: "AI-powered platform for creating learning materials, online tests, and feedback. Features AI-based teacher selection to best meet specific needs.",
          date: "Ongoing",
          logo: "campusai.webp",
          icon: "fas fa-robot",
          iconBg: "bg-blue-900/50",
          iconColor: "text-blue-400",
          tags: ["Next.js", "React.js", "Prisma", "Supabase", "Firebase", "Tailwind V4", "OpenAI", "Vitest"],
          link: "https://www.campusai.ch",
        },
        { title:"SecureDev AI – Security & OWASP Scanner",
          desc: "Security testing platform built with Node.js & Vue.js. Scans URLs and source code for vulnerabilities, provides OWASP Top 10 issue evaluation, and offers AI-driven remediation suggestions via API.",
          date: "2026",
          logo: "sec_ai.png",
          icon: "fas fa-shield-alt",
          iconBg: "bg-red-900/50",
          iconColor: "text-red-400",
          tags: ["Vue.js", "Vite", "Tailwind CSS", "Lucide Vue", "PostCSS", "AI Security"],
          link: "https://secure-dev-ai.vercel.app/",
        },
        { title:"Ali Baba Yöresel – E-Commerce & CRM",
          desc: "Complete e-commerce & CRM platform with Admin Portal. Concept, development, deployment, and maintenance carried out completely independently.",
          date: "2026",
          logo: "alibaba.png",
          icon: "fas fa-shopping-cart",
          iconBg: "bg-purple-900/50",
          iconColor: "text-purple-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://www.alibabayoresel.com.tr",
        },
        { title:"Sefa Metzgerei – E-Commerce & Admin Portal",
          desc: "Professional e-commerce platform with admin management for a butchery. Completely independently developed, deployed, and maintained.",
          date: "2026",
          logo: "sefa_metz.jpg",
          icon: "fas fa-store",
          iconBg: "bg-green-900/50",
          iconColor: "text-green-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://plus-metz.vercel.app",
        },
        { title:"Data Hackdays Uri 2025",
          desc: "Integration Monitoring Project. Developed frontend independently within 2 days and hosted on AWS S3. Combined demographic & social data.",
          date: "April 2025",
          logo: "hoi_uri.png",
          icon: "fas fa-chart-bar",
          iconBg: "bg-orange-900/50",
          iconColor: "text-orange-400",
          tags: ["Vue.js", "Vite", "Tailwind CSS", "Leaflet", "FullCalendar", "AWS S3"],
          link: "https://cumathka.github.io/hoi_ui/#/",
        },
        { title:"Design Bees – Angular & Java",
          desc: "Team-based 6-month project with Java OOP, Angular frontend, MySQL database management, CI/CD pipelines, and project management with Jira.",
          date: "Aug 2022 – Feb 2023",
          logo: "designbees.png",
          icon: "fas fa-code",
          iconBg: "bg-indigo-900/50",
          iconColor: "text-indigo-400",
          tags: ["Java", "Angular", "MySQL", "CI/CD", "Jira", "Scrum"],
          link: "https://designbees.ch/",
        }
      ],
    },
    experience: {
      subtitle: "My Career",
      title: "Professional Experience",
      jobs: [
        {
          title: "Volunteer Fullstack Developer",
          company: "Design Bees, Zurich (Remote)",
          period: "Aug 2022 – Feb 2023",
          points: [
            "Development with Java Spring Boot and Angular",
            "Collaboration within the team and participation in team activities",
            "Application of common development techniques and tools",
          ],
        },
        {
          title: "3-Axis CNC Machine Operator",
          company: "Woodworking, Hatay, Turkey",
          period: "Nov 2019 – May 2021",
          points: [
            "Operation of 3-axis CNC machines for wood",
            "Creation of production plans",
            "Alphacam 3D program application",
          ],
        },
        {
          title: "Textile Planning Specialist",
          company: "Karaman Textile, Samsun, Turkey",
          period: "Dec 2016 – Aug 2017",
          points: [
            "Planning and coordination of textile production processes",
            "Optimization of production workflows",
          ],
        },
        {
          title: "Mathematics Teacher",
          company: "State Schools – Ministry of National Education, Turkey",
          period: "Sep 2007 – Aug 2016",
          points: [
            "Teaching Mathematics and Science",
            "Training in educational technologies",
            "Development of e-learning content",
          ],
        },
      ],
    },
    education: {
      subtitle: "My Background",
      title: "Education",
      items: [
        {
          title: "AWS Re-Start + Cloud Course",
          institution: "AWS / Cloud Bootcamp",
          year: "2023",
          items: [
            "AWS Services (EC2, S3, IAM)",
            "Cloud Security",
            "Terraform & CloudFormation",
            "Automation",
          ],
        },
        {
          title: "Full Stack Web Development",
          institution: "Hi-Coders (15 months)",
          year: "2022",
          items: [
            "HTML, CSS, JavaScript",
            "React, Angular, Vue.js",
            "Node.js & Java",
            "Responsive Design",
          ],
        },
        {
          title: "Mathematics & Science Education",
          institution: "Atatürk University, Erzurum",
          year: "2006",
          items: [
            "Pedagogy & Didactics",
            "Physics, Chemistry, Biology",
            "Computer-aided Mathematics",
            "Laboratory Teaching",
          ],
        },
      ],
    },
    certificates: {
      subtitle: "My Achievements",
      title: "Certificates",
      items: courses,
    },
    contact: {
      subtitle: "Write me",
      title: "Contact",
      text: "I look forward to new opportunities. Feel free to contact me!",
      name: "Name",
      email: "Email",
      message: "Message",
      send: "Send Message",
      placeholder: {
        name: "Your Name",
        email: "your@email.com",
        message: "Your Message...",
      },
    },
    footer: {
      rights: "© 2025 Cuma Kaya · Altdorf, Switzerland",
      built: "Built with",
    },
  },
  fr: {
    nav: {
      about: "À propos",
      skills: "Compétences",
      projects: "Projets",
      experience: "Expérience",
      certificates: "Certificats",
      education: "Formation",
      contact: "Contact",
    },
    hero: {
      role: "Développeur Full Stack",
      greeting: "Bonjour, je suis",
      description:
        "Développeur Full Stack Junior. Développement d'applications web performantes assisté par l'IA et technologies modernes comme Vue.js, Node.js, AWS Cloud, Java (Spring), React, Angular, MySQL, Cybersecurity, Ethical Hacking.",
      viewProjects: "Voir Projets",
      contact: "Contact",
      scroll: "Défiler",
    },
    about: {
      subtitle: "Qui suis-je?",
      title: "À propos de moi",
      heading: "Développeur Passionné & Apprenant à Vie",
      p1: "Je suis un Développeur Full Stack Junior avec une certification AWS Cloud Practitioner et un fort intérêt pour les technologies web modernes et les solutions cloud. Mes intérêts techniques incluent Vue.js, React, Angular, Node.js, Java (Spring), MySQL et AWS Cloud, ainsi que les bases de la cybersécurité et du piratage éthique.",
      p2: "Dans mon processus de développement, j'adopte une approche assistée par l'IA et j'utilise activement des outils tels que GitHub Copilot pour améliorer la productivité et accélérer le développement. En travaillant avec des technologies comme Vue.js, Node.js, Java (Spring), React, Angular, MySQL et AWS Cloud, je me concentre sur la création d'applications web performantes et évolutives, en livrant aussi bien des prototypes rapides que des solutions prêtes pour la production.",
      p3: "Ma philosophie de développement repose sur l'écriture d'un code propre et maintenable, la conception d'architectures système évolutives et la création d'excellentes expériences utilisateur. Je m'engage à apprendre en continu, à explorer de nouvelles technologies et à combiner mes connaissances en développement, cloud et sécurité pour concevoir des solutions numériques fiables et efficaces.",
      location: "Lieu",
      email: "E-mail",
      phone: "Téléphone",
      languages: "Langues",
      cert: "Certification",
      license: "Permis",
      stats: {
        projects: "Projets terminés",
        certs: "Certifications",
        training: "Formation Full Stack",
        teaching: "Années d'enseignement",
      },
    },
    skills: {
      subtitle: "Ce que je sais faire",
      title: "Compétences & Technologies",
    },
    projects: {
      subtitle: "Ce que j'ai construit",
      title: "Projets",
      live: "Voir Live",
      items: [
        { title:"CampusAI – Éducation pilotée par l'IA",
          desc: "Plateforme alimentée par l'IA pour créer des supports d'apprentissage, des tests en ligne et des commentaires. Comprend une sélection d'enseignants basée sur l'IA pour mieux répondre aux besoins.",
          date: "En cours",
          logo: "campusai.webp",
          icon: "fas fa-robot",
          iconBg: "bg-blue-900/50",
          iconColor: "text-blue-400",
          tags: ["Next.js", "React.js", "Prisma", "Supabase", "Firebase", "Tailwind V4", "OpenAI", "Vitest"],
          link: "https://www.campusai.ch",
        },
        { title:"SecureDev AI – Sécurité et Scanner OWASP",
          desc: "Plateforme de tests de sécurité avec serveur Node.js & Vue.js. Analyse les URL et le code source à la recherche de failles, évalue les problèmes du top 10 de l'OWASP et propose des suggestions de résolution par l'IA via des clés API.",
          date: "2026",
          logo: "sec_ai.png",
          icon: "fas fa-shield-alt",
          iconBg: "bg-red-900/50",
          iconColor: "text-red-400",
          tags: ["Vue.js", "Vite", "Tailwind CSS", "Lucide Vue", "PostCSS", "AI Security"],
          link: "https://secure-dev-ai.vercel.app/",
        },
        { title:"Ali Baba Yöresel – E-Commerce & CRM",
          desc: "Plateforme complète e-commerce & CRM avec Portail Admin. Concept, développement, déploiement et maintenance réalisés entièrement de manière indépendante.",
          date: "2026",
          logo: "alibaba.png",
          icon: "fas fa-shopping-cart",
          iconBg: "bg-purple-900/50",
          iconColor: "text-purple-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://www.alibabayoresel.com.tr",
        },
        { title:"Sefa Metzgerei – E-Commerce & Portail Admin",
          desc: "Plateforme e-commerce professionnelle avec gestion administrative pour une boucherie. Entièrement développé, déployé et maintenu de manière indépendante.",
          date: "2026",
          logo: "sefa_metz.jpg",
          icon: "fas fa-store",
          iconBg: "bg-green-900/50",
          iconColor: "text-green-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://plus-metz.vercel.app",
        },
        { title:"Data Hackdays Uri 2025",
          desc: "Projet de surveillance de l'intégration. Frontend développé indépendamment en 2 jours et hébergé sur AWS S3. Données démographiques et sociales combinées.",
          date: "Avril 2025",
          logo: "hoi_uri.png",
          icon: "fas fa-chart-bar",
          iconBg: "bg-orange-900/50",
          iconColor: "text-orange-400",
          tags: ["Vue.js", "Vite", "Tailwind CSS", "Leaflet", "FullCalendar", "AWS S3"],
          link: "https://cumathka.github.io/hoi_ui/#/",
        },
        { title:"Design Bees – Angular & Java",
          desc: "Projet de 6 mois en équipe avec Java OOP, frontend Angular, gestion de base de données MySQL, pipelines CI/CD et gestion de projet avec Jira.",
          date: "Aoû 2022 – Fév 2023",
          logo: "designbees.png",
          icon: "fas fa-code",
          iconBg: "bg-indigo-900/50",
          iconColor: "text-indigo-400",
          tags: ["Java", "Angular", "MySQL", "CI/CD", "Jira", "Scrum"],
          link: "https://designbees.ch/",
        }
      ],
    },
    experience: {
      subtitle: "Mon parcours",
      title: "Expérience Professionnelle",
      jobs: [
        {
          title: "Développeur Fullstack Bénévole",
          company: "Design Bees, Zurich (Télétravail)",
          period: "Aoû 2022 – Fév 2023",
          points: [
            "Développement avec Java Spring Boot et Angular",
            "Collaboration en équipe et participation aux activités d'équipe",
            "Utilisation des techniques et outils de développement courants",
          ],
        },
        {
          title: "Opérateur CNC 3 Axes",
          company: "Travail du bois, Hatay, Turquie",
          period: "Nov 2019 – Mai 2021",
          points: [
            "Utilisation de machines CNC 3 axes pour le bois",
            "Création de plans de production",
            "Application du programme Alphacam 3D",
          ],
        },
        {
          title: "Spécialiste Planification Textile",
          company: "Karaman Textile, Samsun, Turquie",
          period: "Déc 2016 – Aoû 2017",
          points: [
            "Planification et coordination des processus de production textile",
            "Optimisation des flux de production",
          ],
        },
        {
          title: "Professeur de Mathématiques",
          company:
            "Écoles publiques – Ministère de l'Éducation Nationale, Turquie",
          period: "Sep 2007 – Aoû 2016",
          points: [
            "Enseignement des mathématiques et des sciences",
            "Formation aux technologies éducatives",
            "Développement de contenu e-learning",
          ],
        },
      ],
    },
    education: {
      subtitle: "Mon parcours",
      title: "Formation",
      items: [
        {
          title: "AWS Re-Start + Cours Cloud",
          institution: "AWS / Cloud Bootcamp",
          year: "2023",
          items: [
            "Services AWS (EC2, S3, IAM)",
            "Sécurité Cloud",
            "Terraform & CloudFormation",
            "Automatisation",
          ],
        },
        {
          title: "Développement Web Full Stack",
          institution: "Hi-Coders (15 mois)",
          year: "2022",
          items: [
            "HTML, CSS, JavaScript",
            "React, Angular, Vue.js",
            "Node.js & Java",
            "Responsive Design",
          ],
        },
        {
          title: "Master Enseignement Math. & Sc.",
          institution: "Université Atatürk, Erzurum",
          year: "2006",
          items: [
            "Pédagogie & Didactique",
            "Physique, Chimie, Biologie",
            "Mathématiques assistées par ordinateur",
            "Enseignement en laboratoire",
          ],
        },
      ],
    },
    certificates: {
      subtitle: "Mes Réalisations",
      title: "Certificats",
      items: courses,
    },
    contact: {
      subtitle: "Écrivez-moi",
      title: "Contact",
      text: "Je suis ouvert à de nouvelles opportunités. N'hésitez pas à me contacter !",
      name: "Nom",
      email: "E-mail",
      message: "Message",
      send: "Envoyer Message",
      placeholder: {
        name: "Votre Nom",
        email: "votre@email.com",
        message: "Votre Message...",
      },
    },
    footer: {
      rights: "© 2025 Cuma Kaya · Altdorf, Suisse",
      built: "Construit avec",
    },
  },
  tr: {
    nav: {
      about: "Hakkımda",
      skills: "Yetenekler",
      projects: "Projeler",
      certificates: "Sertifikalar",
      experience: "Deneyim",
      education: "Eğitim",
      contact: "İletişim",
    },
    hero: {
      role: "Full Stack Geliştirici",
      greeting: "Merhaba, ben",
      description:
        "Junior Full Stack Geliştirici. AI destekli geliştirme, Vue.js, Node.js, AWS Cloud, Java (Spring), React, Angular, MySQL, Cybersecurity, Ethical Hacking gibi modern teknolojilerle yüksek performanslı web uygulamaları geliştiriyorum.",
      viewProjects: "Projeleri Gör",
      contact: "İletişim",
      scroll: "Kaydır",
    },
    about: {
      subtitle: "Ben kimim?",
      title: "Hakkımda",
      heading: "Tutkulu Geliştirici & Yaşam Boyu Öğrenci",
      p1: "Modern web teknolojilerine ve bulut tabanlı çözümlere yoğun ilgi duyan, AWS Cloud Practitioner sertifikasına sahip bir Junior Full-Stack Geliştiriciyim. Teknik ilgi alanlarım arasında Vue.js, React, Angular, Node.js, Java (Spring), MySQL ve AWS Cloud'un yanı sıra siber güvenlik ve etik hackleme temelleri bulunmaktadır.",
      p2: "Geliştirme sürecimde AI destekli bir yaklaşım benimsiyor ve üretkenliği artırmak, geliştirmeyi hızlandırmak için uyumlu olarak GitHub Copilot gibi araçları aktif olarak kullanıyorum. Vue.js, Node.js, Java (Spring), React, Angular, MySQL ve AWS Cloud gibi teknolojilerle çalışarak, hem hızlı prototipler hem de üretime hazır çözümler sunarak yüksek performanslı ve ölçeklenebilir web uygulamaları oluşturmaya odaklanıyorum.",
      p3: "Geliştirme felsefem, temiz ve sürdürülebilir kod yazmaya, ölçeklenebilir sistem mimarileri tasarlamaya ve mükemmel kullanıcı deneyimleri yaratmaya dayanmaktadır. Sürekli öğrenmeye, yeni teknolojileri keşfetmeye ve güvenilir, verimli dijital çözümler oluşturmak için geliştirme, bulut ve güvenlik bilgisini birleştirmeye kararlıyım.",
      location: "Konum",
      email: "E-posta",
      phone: "Telefon",
      languages: "Diller",
      cert: "Sertifika",
      license: "Ehliyet",
      stats: {
        projects: "Tamamlanan Projeler",
        certs: "Sertifikalar",
        training: "Full Stack Eğitimi",
        teaching: "Yıl Öğretmenlik Deneyimi",
      },
    },
    skills: {
      subtitle: "Neler yapabilirim",
      title: "Yetenekler & Teknolojiler",
    },
    projects: {
      subtitle: "Neler geliştirdim",
      title: "Projeler",
      live: "Canlı Gör",
      items: [
        { title:"CampusAI – Yapay Zeka Destekli Eğitim",
          desc: "Yapay zeka ile öğrenme materyalleri hazırlama, online test çözme ve hatalara geri bildirim sağlayan platform. İhtiyaca en iyi cevap verecek öğretmen seçimini de içerir.",
          date: "Yapım Aşamasında",
          logo: "campusai.webp",
          icon: "fas fa-robot",
          iconBg: "bg-blue-900/50",
          iconColor: "text-blue-400",
          tags: ["Next.js", "React.js", "Prisma", "Supabase", "Firebase", "Tailwind V4", "OpenAI", "Vitest"],
          link: "https://www.campusai.ch",
        },
        { title:"SecureDev AI – Güvenlik ve OWASP Tarayıcı",
          desc: "Node.js sunucusu ve Vue.js ile geliştirilmiş web güvenlik test platformu. URL ve kaynak kodlarındaki güvenlik açıklarını tarar, OWASP Top 10 değerlendirmeleri yapar ve API anahtarı kullanılarak yapay zeka destekli düzeltme önerileri sunar.",
          date: "2026",
          logo: "sec_ai.png",
          icon: "fas fa-shield-alt",
          iconBg: "bg-red-900/50",
          iconColor: "text-red-400",
          tags: [
            "Vue.js",
            "Node.js",
            "Yapay Zeka Destekli Güvenlik",
            "OWASP 10",
          ],
          link: "https://secure-dev-ai.vercel.app/",
        },
        { title:"Ali Baba Yöresel – E-Ticaret & CRM",
          desc: "Admin Portalı ile tam kapsamlı e-ticaret ve CRM platformu. Konsept, geliştirme, yayınlama ve bakım tamamen bağımsız olarak gerçekleştirildi.",
          date: "2026",
          logo: "alibaba.png",
          icon: "fas fa-shopping-cart",
          iconBg: "bg-purple-900/50",
          iconColor: "text-purple-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://www.alibabayoresel.com.tr",
        },
        { title:"Sefa Metzgerei – E-Ticaret & Admin Portalı",
          desc: "Bir kasap için admin yönetimine sahip profesyonel e-ticaret platformu. Tamamen bağımsız olarak geliştirildi, yayınlandı ve bakımı yapıldı.",
          date: "2026",
          logo: "sefa_metz.jpg",
          icon: "fas fa-store",
          iconBg: "bg-green-900/50",
          iconColor: "text-green-400",
          tags: ["Vue.js", "Vite", "Firebase", "Pinia", "Vue Router", "Bootstrap", "VueDraggable"],
          link: "https://plus-metz.vercel.app",
        },
        { title:"Data Hackdays Uri 2025",
          desc: "Entegrasyon İzleme Projesi. Frontend 2 gün içinde bağımsız olarak geliştirildi ve AWS S3 üzerinde barındırıldı. Demografik ve sosyal veriler birleştirildi.",
          date: "Nisan 2025",
          logo: "hoi_uri.png",
          icon: "fas fa-chart-bar",
          iconBg: "bg-orange-900/50",
          iconColor: "text-orange-400",
          tags: ["Vue.js", "Vite", "Tailwind CSS", "Leaflet", "FullCalendar", "AWS S3"],
          link: "https://cumathka.github.io/hoi_ui/#/",
        },
        { title:"Design Bees – Angular & Java",
          desc: "Java OOP, Angular frontend, MySQL veritabanı yönetimi, CI/CD pipeline'ları ve Jira ile proje yönetimi içeren 6 aylık takım tabanlı proje.",
          date: "Ağu 2022 – Şub 2023",
          logo: "designbees.png",
          icon: "fas fa-code",
          iconBg: "bg-indigo-900/50",
          iconColor: "text-indigo-400",
          tags: ["Java", "Angular", "MySQL", "CI/CD", "Jira", "Scrum"],
          link: "https://designbees.ch/",
        }
      ],
    },
    experience: {
      subtitle: "Kariyerim",
      title: "Profesyonel Deneyim",
      jobs: [
        {
          title: "Gönüllü Fullstack Geliştirici",
          company: "Design Bees, Zürih (Uzaktan)",
          period: "Ağu 2022 – Şub 2023",
          points: [
            "Java Spring Boot ve Angular ile geliştirme",
            "Takım içi işbirliği ve ekip aktivitelerine katılım",
            "Yaygın geliştirme teknikleri ve araçlarının kullanımı",
          ],
        },
        {
          title: "3 Eksenli CNC Makine Operatörü",
          company: "Ahşap İşleme, Hatay, Türkiye",
          period: "Kas 2019 – May 2021",
          points: [
            "Ahşap için 3 eksenli CNC makinelerinin kullanımı",
            "Üretim planlarının oluşturulması",
            "Alphacam 3D program uygulaması",
          ],
        },
        {
          title: "Tekstil Planlama Uzmanı",
          company: "Karaman Tekstil, Samsun, Türkiye",
          period: "Ara 2016 – Ağu 2017",
          points: [
            "Tekstil üretim süreçlerinin planlanması ve koordinasyonu",
            "Üretim akışlarının optimizasyonu",
          ],
        },
        {
          title: "Matematik Öğretmeni",
          company: "Devlet Okulları – Milli Eğitim Bakanlığı, Türkiye",
          period: "Eyl 2007 – Ağu 2016",
          points: [
            "Matematik ve Fen Bilimleri Öğretimi",
            "Eğitim teknolojileri eğitimi",
            "E-öğrenme içeriği geliştirme",
          ],
        },
      ],
    },
    education: {
      subtitle: "Geçmişim",
      title: "Eğitim",
      items: [
        {
          title: "AWS Re-Start + Bulut Kursu",
          institution: "AWS / Cloud Bootcamp",
          year: "2023",
          items: [
            "AWS Hizmetleri (EC2, S3, IAM)",
            "Bulut Güvenliği",
            "Terraform & CloudFormation",
            "Otomasyon",
          ],
        },
        {
          title: "Full Stack Web Geliştirme",
          institution: "Hi-Coders (15 ay)",
          year: "2022",
          items: [
            "HTML, CSS, JavaScript",
            "React, Angular, Vue.js",
            "Node.js & Java",
            "Responsive Tasarım",
          ],
        },
        {
          title: "Matematik & Fen Bil. Eğitimi",
          institution: "Atatürk Üniversitesi, Erzurum",
          year: "2006",
          items: [
            "Pedagoji & Didaktik",
            "Fizik, Kimya, Biyoloji",
            "Bilgisayar Destekli Matematik",
            "Laboratuvar Öğretimi",
          ],
        },
      ],
    },
    certificates: {
      subtitle: "Başarılarım",
      title: "Sertifikalar",
      items: courses,
    },
    contact: {
      subtitle: "Bana yazın",
      title: "İletişim",
      text: "Yeni fırsatlara açığım. Benimle iletişime geçmekten çekinmeyin!",
      name: "İsim",
      email: "E-posta",
      message: "Mesaj",
      send: "Mesaj Gönder",
      placeholder: {
        name: "İsminiz",
        email: "senin@email.com",
        message: "Mesajınız...",
      },
    },
    footer: {
      rights: "© 2025 Cuma Kaya · Altdorf, İsviçre",
      built: "ile yapıldı",
    },
  },
};

export function useLanguage() {
  const t = computed(() => translations[currentLang.value]);

  const setLanguage = (lang) => {
    if (translations[lang]) {
      currentLang.value = lang;
    }
  };

  return {
    currentLang,
    t,
    setLanguage,
  };
}
